version: "3.4"
services:
  app:
    container_name: api-documentation-backend-ecommerce-desa-belega
    image: desa-belega/api-documentation-backend-ecommerce-desa-belega
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    environment:
      - SERVICE_PORT=${SERVICE_PORT}
    ports:
      - ${SERVICE_PORT}:${SERVICE_PORT}
    networks:
      - ecommerce-desa-belega

networks:
  ecommerce-desa-belega:
    driver: bridge

